services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: (your-host)
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: elektra64
      - key: DB_USERNAME
        value: elektra64_user
      - key: DB_PASSWORD
        value: your_password
